name: Upload to Google Drive (OAuth)

on:
  push:
    branches:
      - develop

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zip
          zip -r archive.zip *

      - name: Upload to Google Drive with OAuth
        uses: logickoder/g-drive-upload@main
        with:
          authType: 'oauth'
          clientId: ${{ secrets.GOOGLE_CLIENT_ID }}
          clientSecret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refreshToken: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          filename: 'archive.zip'
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          name: 'documentation.zip'
          overwrite: 'true'
