name: Upload to Google Drive

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test file
        run: |
          echo "Este es un archivo de prueba subido automáticamente el $(date)" > prueba.txt

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: "prueba.txt"
          folderId: ${{ secrets.FOLDER_ID }}
          name: "archivo-prueba.txt"
          overwrite: "true"
